timestamps {
    // Define input parameters for the pipeline, including the default Slack channel as '#notifications'
    properties([
        parameters([
            string(name: 'SLACK_CHANNEL', defaultValue: '#notifications', description: 'Specify the Slack channel for notifications')
        ])
    ])

    node() {
        try {
            stage('first-project-jar - Checkout') {
                checkout([$class: 'GitSCM', branches: [[name: '*/main']], doGenerateSubmoduleConfigurations: false, extensions: [], submoduleCfg: [], userRemoteConfigs: [[credentialsId: '', url: 'https://github.com/TeamITSpark/first-project-jar.git']]]) 
            }

            stage('first-project-jar - compile') {
                // Batch build step
                bat """ 
                mvn clean compile
                """ 
            }

            // Approval before proceeding to package
            stage('Approval') {
                // Wait for user approval to proceed
                input message: 'Proceed to package?', ok: 'Yes, continue', parameters: [
                    string(name: 'SLACK_CHANNEL', defaultValue: params.SLACK_CHANNEL, description: 'Specify the Slack channel for notifications')
                ]
            }

            stage('first-project-jar - package') {
                // Batch build step
                bat """ 
                mvn clean package
                """ 
            }

            stage('first-project-jar - install') {
                // Batch build step
                bat """ 
                mvn clean install
                """ 
            }

        } catch (Exception e) {
            // Rethrow the exception to be caught in the finally block
            throw e
        } finally {
            // Separate Notification Stage
            stage('Notification') {
                // This will handle all notifications after the build process
                if (currentBuild.result == 'SUCCESS') {
                    slackSend (channel: params.SLACK_CHANNEL, color: 'good', message: "Build Success: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                } else if (currentBuild.result == 'FAILURE') {
                    slackSend (channel: params.SLACK_CHANNEL, color: 'danger', message: "Build Failed: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
                }
                // Always notify on completion
                slackSend (channel: params.SLACK_CHANNEL, color: '#FFFF00', message: "Build Completed: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' (${env.BUILD_URL})")
            }
        }
    }
}
